# fmt: off
[
  {
    "name": "filesystem_info",
    "getval": "(?m)^\\s*(?P<size>\\d+)\\s+(?P<free>\\d+)\\s+(?P<type>harddisk)\\s+\\S+\\s+(?P<prefix>\\S+)",
    "result": {
      "fs_health": {
        "total": "{{ size | int }}",
        "free": "{{ free | int }}"
      }
    }
  }
]
# fmt: on