# fmt: off
[
  {
    "name": "power_status",
    "getval": "(?m)^(No power info, as no System Controller Module\\(.*\\) is online\\.)",
    "result": {
      "power": {
        "status": "NotSupported"
      }
    }
  },
  {
    "name": "fan_zone_speed",
    "getval": "(?m)^Fan Zone Speed:\\s*(?P<zone_speed>.+)$",
    "result": {
      "fans": {
        "status": "OK",
        "zone_speed": "{{ zone_speed | trim }}"
      }
    }
  },
  {
    "name": "fan_air_filter",
    "getval": "(?m)^Fan Air Filter\\s*:\\s*(?P<air_filter>.+)$",
    "result": {
      "fans": {
        "air_filter": "{{ air_filter | trim }}"
      }
    }
  },
  {
    "name": "temperature",
    "getval": "(?m)^Temperature:\\s*(?P<current_temp>\\d+)",
    "result": {
      "temperature": {
        "current_temp": "{{ current_temp | int }}"
      }
    }
  }
]
# fmt: on